require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

ENVFILES = {
  'Dev.Release' => '$(PODS_ROOT)/../../.env.dev',
  'Qa.Release' => '$(PODS_ROOT)/../../.env.qa',
  'Prod.Release' => '$(PODS_ROOT)/../../.env.prod',
}

project 'xydti',
        'Dev.Release' => :release,
        'Qa.Release' => :release,
        'Prod.Release' => :release

target 'xydti' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'xydtiTests' do
    inherit! :complete
    # Pods for testing
  end

 # react_native > 0.60，会autolink，但是不会安装 subspecs, 手动定义，虽然会出现警告，但不影响使用
 # 待找到更好的方式后再更新
 pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'FaceDetectorMLKit',
  'BarcodeDetectorMLKit'
 ]

#  pod 'RNBackgroundFetch', path: './BackgroundFetch'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end
  end
end
